- hosts: 192.168.1.28
  tasks:
   # - include_vars: login1.yml
    - name: variable d'authentification
      set_fact:
        os_auth:
          auth_url: http://192.168.1.28:5000/v3/
          username: admin
          password: mind
          project_name: admin
          #os_tenant_name: admin
          project_domain_name: default
          #availability_zone: nova
          user_domain_name: default
          #region_name: RegionOne
          #auth_version: 2    
    - name: create instance
      os_server:
        state: present
        auth: "{{ os_auth }}"
        name: vm-jenkins-s
        image: 'Cloud Ubuntu Server 16.04LTS'
        key_name: soumaya
        timeout: 120
        flavor: LARGE
        network: selfservice
        #floating_ip_pools: provider
        floating_ips:
          - 192.168.1.249
        security_groups: default
wait: yes
